### ISSUE TITLE
evaluate cljs code from source file

### ISSUE THREAD

**Issue by clifford** [Deraen/saapas#11]
Hi Deraen

Firstly thank you so much for putting this project together, it's been a life saver.

I would like to evaluate cljs code directly from the source file. I launched a brepl, following your instructions: boot repl -c

I then tried to 'cider-connect' to this repl from within emacs, but I am not having any luck. It seems to launch a new repl, have you got any suggestions?

Kind Regards
Clifford

**Comment by Deraen** [comment]
Are you also running `boot dev`? The nrepl server is started by that, and `boot repl -c` is only a client, and is not necessary if you are going to connect editor to the nrepl.

I have no idea how Cljs works with Emacs / Cider.

**Comment by Deraen** [comment]
This looks like a good documentation: http://cider.readthedocs.io/en/latest/up_and_running/#browser-connected-clojurescript-repl-in-boot-project
