### ISSUE TITLE
Unable to Auto reload

### ISSUE THREAD

**Issue by karneaud** [Deraen/saapas#14]
I'm using you project template build a web application. 

After getting everything up and running I am unable to reload the project files in the browser to get the changes

this [here](https://github.com/adzerk-oss/boot-reload/issues/91) is my configuration file. I haven't really changed much but I'm not sure what is causing the issue with not being able to reaload/ refresh the browser with the changes.

What can cause the browser not to reload/ auto-fresh?

**Comment by karneaud** [comment]
[my repo](https://github.com/karneaud/saapas-vagrantl)

**Comment by Deraen** [comment]
Example repo doesn't no longer exists so I'm going to close this.
