### ISSUE TITLE
`run-tests` thrown an exception

### ISSUE THREAD

**Issue by nha** [Deraen/saapas#8]
`run-tests` Errors

On latest commit, I get an error when running `boot run-tests` (see below).

Notes : 
- `boot test` runs fine.
- I have `phantom-js` installed (v 2.0.0) (this should probably be in the README by the way)

```
Writing clj_test/suite.cljs...

Writing output.cljs.edn...

Compiling ClojureScript...

• output.js

Running cljs tests...hello world local js

Starting the app

Error: Assert failed: No target specified to om.core/root

(not (nil? target))

/var/folders/0x/gh92nkgj37b3ptlqrbn3tmrc0000gn/T/phantom1975260198908768771.js:74 in onError
```

**Comment by Deraen** [comment]
Will need next version of boot-cljs-test.
